= Skimpy OOP: Introduction to Object-Oriented Programming Using Java
:author: Tim McMichael
:doctype: book
:toc: left
:toc-title: Skimpy Contents
:toclevels: 2
:icons: font
:source-highlighter: pygments
:multipage-level: 1

// TODO: Add link to feedback form in each chapter (and in frontal matter)
// https://forms.gle/4173pZ1yPuNX7pku6

[preface]
== Skimpy Preface: An Excuse for the Inadequacies Within

This isn't a real textbook. 
It's not _imaginary_ or anything, it's just missing most of the stuff a real textbook includes. It's, well, skimpy.

This content is intended to be a companion to CIS150AB, which is an introduction to object-oriented programming. Since you'll be attending (or viewing recordings of) lectures, and you'll have access to additional content in Canvas (our LMS), this text doesn't try to cover everything; it tries to give you the basic information you'll need in order to get the most out of that other content.

It's also skimpy because the purpose of this particular course, at least from my perspective, is not to give students a comprehensive look at a programming language.
It's an introductory course that's taken by a variety of students. If you're a coding student--majoring in _Programming and Systems Analysis_ or _Web Design and Development_, for example--you'll take language-specific courses that will get much more detailed, so our goal here is to give you a foundation for that.
If you're majoring in something else, you might never write another line of code after the semester ends--I want you to learn about programming and software development so you can communicate with the coders in your workplace and have a general understanding of how an idea becomes a program or app.

It's also possible that I just don't know very much. 
You know, a skimpy brain.

=== But why are we stuck reading this eBook?

The only reason I wrote this is because real textbooks are expensive. 
As I started to record more and more videos to supplement the real textbook I was using, students had less and less reason to actually read it.
But I can't cover everything we need in my videos, so I started writing content to fill in details I couldn't get to.

To be clear, this *isn't* skimpy just because students don't bother to read textbooks that are dense and detailed.
That sometimes seems true, but you're different; I can tell just by looking at you! 
But I acknowledge that many students prefer video content and in-person instruction rather than reading, so this is my attempt to meet those students halfway.

This eBook might not be very good or very detailed, but it is very free.

// TODO: Update this "under construction" note
#Unfortunately, as of Spring 2025, this book is *too* skimpy and is still being written, so you'll need the textbook listed in Canvas as well--sorry, I just can't type fast enough.# 

=== And why are we using Java instead of *_my_* favorite language?

_Looking at you, Python nerds..._

Okay, there are a few reasons I use Java to teach OOP:

* It's cross-platform, so my students can use Windows, macOS, or Linux machines and I can grade the work without hassle on whatever machine I'm currently using.
* I like the way Java implements OOP, which I think is "stronger" than in Python, for example.
* Java is _strongly, statically typed_, meaning we have to declare data types when we make our variables and that type can't change. I believe this "stricter" approach to data types is better for beginners. 
* Since it uses C syntax, Java skills transfer well to many other languages.
* At https://www.estrellamountain.edu[Estrella Mountain Community College], we have other CIS classes that teach C# (my favorite OOP language) and Python. I want students using something different for this course so that they get exposed to multiple languages before they graduate. 

If I'm doing this right, what you're mostly learning here is a good foundation of OOP (and general programming) skills and concepts.
We happen to be using Java to do that, but these skills transfer to pretty much any other language you want to learn.

== How to Use This Book

Before starting a chapter, review the relevant information on the "overview" page in Canvas.
Then, start reading the chapter in this eBook. 
When you see *Time to Watch*, just watch the embedded (or hyperlinked) YouTube video.
After the video, continue reading the chapter.

== Related Resources

In general, this book includes resources within each chapter. The following links collect those resources so you can find them when necessary.

GitHub landing page: https://timmcmichael.github.io

YouTube channel: https://www.youtube.com/@ProfTimEMCC[@ProfTimEMCC]

Course YouTube playlist: https://www.youtube.com/playlist?list=PL_Lc2HVYD16Y-vLXkIgggjYrSdF5DEFnU[Object-Oriented Progamming Fundamentals (CIS150AB)]

=== Source code files:

The files shown in the eBook and videos can be available on GitHub, and it includes information about how to find and download what you are looking for. 
If you have trouble finding something (or using the GitHub site), please contact me at mailto:tim.mcmichael@estrellamountain.edu[tim.mcmichael@estrellamountain.edu] or in Canvas.

* GitHub: https://github.com/timmcmichael/EMCCTimFiles[https://github.com/timmcmichael/EMCCTimFiles]

_Note: Files are generally linked in Canvas as well_.

include::chapter-0/content.adoc[]

include::chapter-1-coding/content.adoc[]

include::chapter-2-variables/content.adoc[]

include::chapter-3-methods/content.adoc[]

include::chapter-4-classes/content.adoc[]

include::chapter-5-decisions/content.adoc[]

include::chapter-6-loops/content.adoc[]

include::chapter-7-debugging/content.adoc[]

include::chapter-8-arrays/content.adoc[]

include::chapter-9-inheritance/content.adoc[]

include::chapter-10-swing/content.adoc[]

include::back-matter/content.adoc[]

// TODO: Convert all "Intersting" blocks to ==== instead of ----
// TODO: Canvas - update overview competencies to match book/videos
// TODO: Canvas - When finished, Update required textbook to recommended; update Module Overview references to match.
// TODO: Set theme for plantUML renderings: https://the-lum.github.io/puml-themes-gallery/diagrams/Class.html