== 0000 - Getting Started (Chapter 0)

=== What's the Point?
* Install the tools you need to create Java programs

'''

Our goal is to learn the fundamentals of *object-oriented programming* using the *Java* programming language. 
You might not even know what those things mean yet, but to get started you'll need a couple of things installed on your computer.

Java Development Kit (JDK):: A collection of software, used to develop Java programs. Most importantly, it includes a *compiler*.
Integrated Development Environment (IDE):: An application used to write and test source code. 

These two tools can be used on pretty much any laptop or desktop computer, even if it's not very powerful.

.Heads Up!
****
Java development on a chromebook or iPad is tricky and not recommended for beginners. Use a different computer if at all possible.
****

The Canvas course includes some options for students who don't have a computer capable of running the necessary software.

=== Install the Java Development Kit

I recommend installing the JDK available at https://adoptium.net, and the Oracle JDK is another great option.
The linked documents below provide detailed installation instructions--but if they are outdated at the moment, there are about a gazillion web pages and Youtube videos that will show you the process.
I recommend installing the JDK before installing your IDE.

* https://drive.google.com/open?id=1yBFhti2juLLc-GNuxSwj1HBFjxxQL8LMwUBYOLPcUbA&usp=drive_copy[Install JDK on Windows]
* https://drive.google.com/open?id=1lTWz0KQkn3CbfjF4CICLNWpKhO9GedGhkO-SAHPkwAU&usp=drive_copy[Install JDK on macOS]

=== Install an IDE

A computer program is created by writing *source code*, which is just text and can be created using any text editor.
However, developing programs with something like Notepad or TextEdit--which come with Windows and macOS, respectively--means going through some potentially confusing (or at least intimidating) steps each time you want to run your program.
Though IDEs do much more, the most important thing they do for beginners is give you a "run" button you can press whenever you want to test your code.

You can definitely write Java programs without using an IDE, but it's kinda like getting engaged to someone you've only ever met online: just because it turns out okay for some people doesn't mean it's a good idea for you.
The only people who should write code without an IDE already know too much about programming to be wasting their time reading this book.

There are many great IDEs out there, including many free options, and ultimately it doesn't matter which one you use: they all produce the same files, and a person looking at the files can't tell what IDE you used.
It's like choosing between Word and Google Docs; each has strengths and weaknesses, but you can write romantic poems about your online fiancé (or fiancée) in either one.

I primarily use Visual Studio Code ("VS Code"), so that's what you'll see in most of my videos. 
It's completely free and is available for Windows, macOS, and Linux.
You can download it at https://code.visualstudio.com, and the videos below walk through installing VS Code and the tools it needs for Java development.
I recommend installing a JDK (see previous section) prior to installing an IDE.

.Heads Up!
****
Visual Studio *Code* is not the same as Visual Studio! There's a free version of Visual Studio (called Visual Studio Community) but it's not intended to be used with Java. 
You're going to want Visual Studio Code (aka "VS Code") for your Java coding.
****

VS Code Installation guides:

* https://www.youtube.com/watch?v=t1EeX2AKkcY&list=PL_Lc2HVYD16Y-vLXkIgggjYrSdF5DEFnU&index=1[Installing VS Code on Windows for Java]
* https://www.youtube.com/watch?v=iqhgrVWWi78&list=PL_Lc2HVYD16Y-vLXkIgggjYrSdF5DEFnU&index=2[Installing VS Code on macOS for Java]

Once you've installed the JDK and VS Code (along with the Java extensions), you're ready to create your first program. 

[.Check Your Learning]
****
Can you answer these questions?

1. What does JDK stand for?

2. What is an example of an Integrated Development Environment?
****