:imagesdir: images
:sourcedir: source
// The following corrects the directories if this is included in the index file.
ifeval::["{docname}" == "index"]
:imagesdir: chapter-1/images
:sourcedir: chapter-1/source
endif::[]

== Stuff That's Tacked on the End

=== Answers to _Check Your Learning_ questions

==== Getting Started Chapter
....
1. What does JDK stand for?
    Java Development Kit

2. What is an example of an Integrated Development Environment?
    Visual Studio Code, eclipse, IntelliJ, and many others.
....

==== Computers and Coding (Chapter 1)
....
1. What tool converts your programming into something the computer can run?
    A compiler (or, in some cases, interpreter)

2. What is the name of the instruction set, specific to each computer type, that a computer can understand and execute?
    Machine language

3. What are some advantages of using an organized software development process?
    Keeps you focused, breaks up a complicated problem/program, etc.

4. What programming paradigm bundles procedures with the data they use?
    Object-oriented programming (OOP)
....
