=== Defininte vs Indefinite Loops
Loops fall into two broad categories: definite and indefinite.

A _definite loop_ is one that repeats a specific number of times. 
At the time the loop starts, it has already been determined exactly how many times it will repeat.
The _programmer_ might not know at the time of writing the program--for example, if the number of times the loop repeats is based on user input--but the condition that determines how many times the loop will repeat is known before the loop starts.

And example of a definite loop a loop that prints out the name of every student on a roster. 
The program checks the number of students on the roster, and that count is the number of times the loop will repeat.
Definite loops are also called _counter controlled loops_ because the programmer uses a counter variable to keep track of how many times the loop has repeated.

An _indefinite loop_ is one that repeats until a certain condition is met.
It can't be known how many times the loop will repeat until it's actually running.
The loop begins it's first iteration, and the condition that determines whether the loop will repeat is checked.
That condition might be based on user input, the state of the program, or some other factor that can't be determined until the program is running.

An example of an indefinite loop is a prompt that asks the user to input their password, and keeps repeating until the user's input is correct.
The user might input the correct password the first time, it might take 3 tries, or it might take 100 tries.
The program doesn't know and is just going to repeat until the user gets it right.
This type of loop is sometimes called a _sentinel controlled loop_ because the loop repeats until a "sentinel" value is encountered--a signal that the loop should stop.

Any of the Java loop structures can be used to create either a definite or an indefinite loop.
However, some of the loop structures are better suited to one type of loop or the other, so it's good to think about what kind of loop you need before you start writing your code.
