:imagesdir: images
:sourcedir: source
// The following corrects the directories if this is included in the index file.
ifeval::["{docname}" == "index"]
:imagesdir: chapter-5-decisions/images
:sourcedir: chapter-5-decisions/source
endif::[]

== 0101 - Decisions

//TODO: Need this "video has more" disclaimer elsewhere?
*_Note: the videos in this chapter go a little beyond the content in the corresponding sections--they show how to write the code, but also show how to apply some things to our class and object design. If you skip the videos, you might miss information needed for the assignments and/or quiz._*

.Help Make These Materials Better!
****
I am actively working to complete and revise this eBook and the accompanying videos. Please consider using the following link to provide feedback and notify me of typos, mistakes, and suggestions for either the eBook or videos:

https://forms.gle/4173pZ1yPuNX7pku6[CIS150AB Course Materials Feedback (Google Form)^]
****

:sectnums!:
=== What's the Point?
* Understand Boolean expressions
* Implement `if` and `if-else` statements
* Use `else if` and nested `if-else` statements
* Apply decision structures to object-oriented programming 


_Source code examples from this chapter and associated videos are available on https://github.com/timmcmichael/EMCCTimFiles/tree/4bf0da6df6f4fe3e3a0ccd477b4455df400cffb6/OOP%20with%20Java%20(CIS150AB)/05%20Decisions[GitHub^]._

:sectnums:
'''

Decisions, or _branching_ gives our programs the ability to execute different code depending on what's happening as it runs.
At the core of decisions is the concept of Boolean logic, which is named after a 19th-century mathematician named George Boole.
Boolean logic is the foundation of the `if` statements that will be the foundation of our branching code.

=== Boolean Expressions

Until now, our programs have all executed very sequentially and predictably--one line of code after another.
How boring!
To give our programs the ability to _branch_ and execute different code based on different conditions, we need to introduce the concept of _decisions_.

In computer programming, a decision is made based on a *Boolean expression*, which is an expression that evaluates to either `true` or `false`.
Think of them as questions that can be answered with a simple "yes" or "no".
_Is this student's GPA high enough to qualify for the scholarship? Has this cell phone customer used all of their data? Did the user enter "exit"?_

The `true` or `false` value of a Boolean expression can be used to determine which code block will execute next, so it's important to understand how they work. 


.Time To Watch!
****
Boolean Logic in Java

// https://youtu.be/npMQkQ2oCAU

video::npMQkQ2oCAU[youtube, list=PL_Lc2HVYD16Y-vLXkIgggjYrSdF5DEFnU]
// File from video:

// * N/A
****

==== Boolean Values

The simplest way to use Boolean in Java is with the keywords `true` and `false`.
These can be assigned to variables of type `boolean`:

[source,java]
----
boolean isTimAmazing = true;
boolean isClassBoring = false;
----

==== Relational Operations
Also known as _comparison operations_, relational operations are expressions that compare two values. 
You will remember them from math class. _Is `x` greater than `y`? Is `a` less than or equal to `10`? Is `c` equal to `d`?_
Relational operators, like arithmetic operators, are _binary_ operators that require two operands. 
In other words, you need two values to compare.
In your math class, you could draw symbols that aren't on your keyboard, like a &#8805; for "greater than or equal to."
In Java, where we have to stick with stuff on our keyboard, we use the following symbols:

.Java relational operators
[cols="1,5", %header, stripes=even,width="50%"]
|===
|*Operator* |*Description*
| `==`
| Equality (checks if two values are equal)
| `!=`
| Inequality (checks if two values are not equal)
| `<`
| Less-than
| `>`
| Greater-than
| `&lt;&#61;`
| Less-than-or-equal-to
| `>=`
| Greater-than-or-equal-to operator.
|===

A relational operation will always evaluate to either `true` or `false`.
We can store that result in a `boolean` variable, as shown below, and we'll also learn how to use these expressions in `if` statements later in this chapter.

[source,java]
----
boolean canBuyAlcohol = age >= 21;
boolean isNegative = number < 0;
----

These assignment statements work like any other: the expression to the right of the equals symbol is evaluated, and the result is stored in the variable on the left.

==== Testing a String for Equality

In Java, you can't use the `==` operator to compare two strings.
The following code will not work as you might expect:

.Example of an incorrect `String` comparison.
[source,java]
----
// Should output "true", but (sometimes) doesn't
String name = "Paul McCartney";
System.out.print("Is this person Paul McCartney?");
System.out.println(name == "Paul McCartney");   // DON'T DO THIS!
----

The `==` operator does not compare the contents of the strings, but rather the memory addresses where the strings are stored.
Due to the nuances of how the Java runtime handles `String` objects, this code will work sometimes, by coincidence, but it's not reliable.

Instead, you'll need to use the `equals()` method, which is a method of the `String` class and gets called using dot notation.
This method will examine the contents of the strings and return `true` if they are the same, and `false` if they are different.

.Example of a correct `String` comparison.
[source,java]
----
// Outputs "true"
String name = "Paul McCartney";
System.out.print("Is this person Paul McCartney? ");
System.out.println(name.equals("Paul McCartney"));
----

=== if Statements

The `if` statement is the most basic decision-making structure in Java.
It allows you to execute a block of code only if a certain condition is true.

The syntax of an `if` statement is the keyword `if`, followed by a Boolean expression in parentheses, followed by a block of code in curly braces.
If the Boolean expression evaluates to `true`, the block of code will execute.
If the Boolean expression evaluates to `false`, the block of code will be skipped.
In either case the program will continue executing the next line of code after the `if`-block.

.Example of an `if` Statement.
[source,java]
----
int age = 20;
if (age < 21) {
    System.out.println("You can't buy alcohol.");
}
System.out.println("Keep that in mind when you go to the store!");
----

In this example, the `if` statement checks if the variable `age` is less than `21`.
Since `20` is less than `21`, the Boolean expression evaluates to `true`, and the block of code inside the `if` statement is executed--and it prints "You can't buy alcohol."
The program then continues to the next line of code, which prints "Keep that in mind when you go to the store!"

If the value of `age` were `22`, the Boolean expression would evaluate to `false`, and the block of code inside the `if` statement would be skipped.
The program would then continue to the next line of code, which prints "Keep that in mind when you go to the store!"

Keep in mind, the parentheses after the `if` keyword can contain any Boolean expression--not just this simple example.

=== Adding an `else` Block

An `if` statement simply determines whether or not to execute a single block of code.
If you want to choose between two blocks of code, you can add an `else` block to the `if` statement.
The syntax is simple: after the `if` block, add the keyword `else`, followed by a block of code in curly braces.

.Example of an `if-else` Statement.
[source,java]
----
int age = 20;
if (age < 21) {
    System.out.println("You can't buy alcohol.");
}
else {
    System.out.println("You can buy alcohol.");
}
System.out.println("Keep that in mind when you go to the store!");
----

An `if-else` statement will always execute one block of code or the other, but never both.
Basically, it's an either-or situation.

.Time To Watch!
****
if and if-else Statements in Java

// https://youtu.be/YytQwS4F6fE

video::YytQwS4F6fE[youtube, list=PL_Lc2HVYD16Y-vLXkIgggjYrSdF5DEFnU]
File from video:

* Completed code: https://raw.githubusercontent.com/timmcmichael/EMCCTimFiles/refs/heads/main/OOP%20with%20Java%20(CIS150AB)/05%20Decisions/MadJokes.java[`MadJokes.java`^]

****

.Interesting!
****
Java includes a shorthand form of an if-else statement called the _ternary operator_, which uses the question mark symbol. It's a useful little trick, but it can be confusing for beginner--and for the people reading your code later. We won't look at them in this course, but a web search should turn up plenty of examples if you are curious.

Assignments in my course require you to actually use if-else statements, so you shouldn't use the ternary operator in code you submit to me.
****

=== The `if-else if` Structure

The `if-else` structure is great for choosing between two blocks of code, but what if you have more than two options?
To handle this, you can chain multiple `if-else` statements together.

.`WeatherRecord.java` (excerpt). Example of an `if-else if` statement. See https://github.com/timmcmichael/EMCCTimFiles/tree/4bf0da6df6f4fe3e3a0ccd477b4455df400cffb6/OOP%20with%20Java%20(CIS150AB)/05%20Decisions[GitHub^] for the full file.
[source,java]
----
public class WeatherRecord {
    // Fields
    private String date;
    private int highTemperature;
    private double averageWindSpeed;

    public String getTempDescription() {
        if (this.highTemperature > 90) {
            return "Hot";
        } else if (this.highTemperature > 70) {
            return "Warm";
        } else if (this.highTemperature > 50) {
            return "Cool";
        } else {
            return "Cold";
        }
    }
}
----

In this example, the `getDescription()` method will return a `String` that describes the weather based on the high temperature of the day.

* If the high temperature is greater than `90`, the method will return "Hot".
* If the high temperature is greater than `70`, the method will return "Warm".
* If the high temperature is greater than `50`, the method will return "Cool".
* If the high temperature is `50` or less, the method will return "Cold".

The code begins with the first statement, and if it evaluates to `true`, the corresponding block of code will execute.
If the first statement evaluates to `false`, the program will move on to the next `else if` statement, and so on.
Once a code block is executed, it will hit a `return` statement, which will exit the method and not evaluate any other blocks of code.
Therefore, only one block of code will execute.
If the program gets through the entire structure without finding a `true` condition, it will execute the block of code in the `else` block, if one is present.

If you're looking at that code critically, you might notice that the `else` block is not strictly necessary. 
You could just put the `return "Cold";` statement at the end of the method, and it would work the same way. 
However, that depends on the logic of the `if-else if` structure and whether or not you're using `return` statements in the blocks of code.

.Interesting!
****
The above example shows one clever use of decisions in an object class. You'd think that a `getDescription()` method would return the value of a field called `description`, but there is no field. Instead, it just uses a decision structure to return a description based on the `highTemperature` field.
****

In summary, An `if-else if` structure can execute, at most, one block of code. 
If an `else` block is included at the end, it guarantees that exactly one block of code will execute.

.Time To Watch!
****
`if-else if` Statements in Java

_Note: This video also shows how to use `if` statements in an OOP context, specifically to help with encapsulation._

// https://youtu.be/ismb63p4N4A

video::ismb63p4N4A[youtube, list=PL_Lc2HVYD16Y-vLXkIgggjYrSdF5DEFnU]
Files from video:

* Starter code: https://raw.githubusercontent.com/timmcmichael/EMCCTimFiles/refs/heads/main/OOP%20with%20Java%20(CIS150AB)/05%20Decisions/K12Student.java[`K12Student.java`^]
* Starter file: https://raw.githubusercontent.com/timmcmichael/EMCCTimFiles/refs/heads/main/OOP%20with%20Java%20(CIS150AB)/05%20Decisions/K12StudentDemo.java[`K12StudentDemo.java`^]

* Completed code: https://raw.githubusercontent.com/timmcmichael/EMCCTimFiles/refs/heads/main/OOP%20with%20Java%20(CIS150AB)/05%20Decisions/K12StudentFinished.java[`K12StudentFinished.java`^]
* Completed code: https://raw.githubusercontent.com/timmcmichael/EMCCTimFiles/refs/heads/main/OOP%20with%20Java%20(CIS150AB)/05%20Decisions/K12StudentDemoFinished.java[`K12StudentDemo.java`^]
****

=== Nested if-else Statements

If we want a block of code to execute only if two different conditions are met, we can place `if` statements inside of each other--which is called _nesting_.
Nested if statements check multiple conditions in a hierarchical way: if one condition is met, it will proceed and check the next condition; if the first condition is not met, it will skip the inner `if` block.

.Basic structure of a nested `if-else` statement.
[source,java]
----
if (condition1) {
    if (condition2) {
        // executes if both condition1 and condition2 are true
    }
    else {
        // executes if condition1 is true and condition2 is false
    }
}
else {
    // executes if condition1 is false
}
----

In the example below, the outermost if-else structure checks the high temperature of the day. 
The if-else structures within those blocks checks the average wind speed and returns an appropriate description.

.`WeatherRecord.java` (excerpt). Example of a nested `if-else` statement. See https://github.com/timmcmichael/EMCCTimFiles/tree/4bf0da6df6f4fe3e3a0ccd477b4455df400cffb6/OOP%20with%20Java%20(CIS150AB)/05%20Decisions[GitHub^] for the full file.
[source,java]
----
public String getFullDescription() {
        if (this.highTemperature > 90) {
            if (this.averageWindSpeed > 10) {
                return "Hot and Windy";
            } else {
                return "Hot";
            }
        } else if (this.highTemperature > 70) {
            if (this.averageWindSpeed > 10) {
                return "Warm and Windy";
            } else {
                return "Warm";
            }
        } else if (this.highTemperature > 50) {
            if (this.averageWindSpeed > 10) {
                return "Cool and Windy";
            } else {
                return "Cool";
            }
        } else {
            if (this.averageWindSpeed > 10) {
                return "Cold and Windy";
            } else {
                return "Cold";
            }
        }
    }
----

.Time To Watch!
****
Nested if-else Statements in Java

// https://youtu.be/bKqlmhtaKd8
video::bKqlmhtaKd8[youtube, list=PL_Lc2HVYD16Y-vLXkIgggjYrSdF5DEFnU]

_Note: This video also shows how to use `if` statements in an OOP context, specifically to help with encapsulation._

Files from video:

* Starter code: https://raw.githubusercontent.com/timmcmichael/EMCCTimFiles/refs/heads/main/OOP%20with%20Java%20(CIS150AB)/05%20Decisions/VinylRecord.java[`VinylRecord.java`^]
* Starter code: https://raw.githubusercontent.com/timmcmichael/EMCCTimFiles/refs/heads/main/OOP%20with%20Java%20(CIS150AB)/05%20Decisions/VinylRecordDemo.java[`VinylRecordDemo.java`^]

* Completed code: https://raw.githubusercontent.com/timmcmichael/EMCCTimFiles/refs/heads/main/OOP%20with%20Java%20(CIS150AB)/05%20Decisions/VinylRecordFinished.java[`VinylRecordFinished.java`^]
* Completed code: https://raw.githubusercontent.com/timmcmichael/EMCCTimFiles/refs/heads/main/OOP%20with%20Java%20(CIS150AB)/05%20Decisions/VinylRecordDemoFinished.java[`VinylRecordDemoFinished.java`^]
****


=== Using Logical Operators
In addition to the relational operators, Java also includes logical operators we can use to make more complex Boolean expressions.
A logical operator is a binary operation, so it takes two operands--but the operands are Boolean expressions instead of numbers.

.Java logical operators
[cols="1,1,5", %header, stripes=even,width="75%"]
|===
| *Operator* |*Name* |*Description*
|`&&`
|AND 
|Evaluates to `true` if *both* operands are `true`
| `\|\|`
| OR
| Evaluates to `true` if *either* operand is `true`
| `!`
| NOT
| Evaluates to `true` if the operand is `false`; evaluates to `false` if the operand is `true`
|===

These operators can be used to combine multiple Boolean expressions into a single, more complex expression.
For example, you could check if a student is eligible for a scholarship based on both their GPA (3.5 or better) and their age (younger than 25).

.Example of a decision using a logical AND operation.
[source,java]
----
if (gpa >= 3.5 && age < 25) {
    System.out.println("You qualify for the scholarship!");
}
----

In this example, the `&&` operator is used to combine two Boolean expressions.
The `if` statement will only execute the block of code if both expressions are `true`.

TIP: Often, the logic you create using an AND operation can be implemented using nested if-else statements, and vice versa.

The OR operation is similar, but only one of the expressions needs to be `true` for the entire expression to be `true`.

.Example of a decision using a logical OR operation.
[source,java]
----
boolean isTimAmazing = false;
boolean isClassFun = true;

if (isTimAmazing || isClassFun) {
    System.out.println("You should take this class!");
}
----

Both operands in an AND or OR operation have to be complete Boolean expressions.
Put another way, each side of the `&&` or `||` operator must be able to evaluate to `true` or `false` on its own.
The following code is a very common beginner mistake and will *not* compile:

`if (percentage >= 80 && < 90) { ... }`

This reads like "if the percentage is greater than or equal to 80 and less than 90," but the second part of the expression is not a complete Boolean expression. 
You need to include the variable name and the comparison operator on both sides of the `&&` operator.

The NOT operation is a little different, as it only takes one operand (making it a _unary_ operator_, if you've nerdy about words, like I am).
It simply inverts the value of the operand.
If the operand is `true`, the NOT operation will evaluate to `false`.
If the operand is `false`, the NOT operation will evaluate to `true`.

.Example of a decision using a logical NOT operation.
[source,java]
----
boolean isTimAmazing = false;

if (!isTimAmazing) {
    System.out.println("At least his mom still loves him!");
}
----

==== Range Checking
There are a lot of situations where you might need to combine multiple conditions to make a decision, but one of the most common is _range checking_.
Range checking means you want to see if a value is within a certain range.

A common example of range checking is to convert a percentage grade to a letter grade.

.Example of range checking using logical operators.
[source,java]
----
public String getLetterGrade(int percentage) {
    if (percentage >= 90 && percentage <= 100) {
        return "A";
    } else if (percentage >= 80 && percentage < 90) {
        return "B";
    } else if (percentage >= 70 && percentage < 80) {
        return "C";
    } else if (percentage >= 60 && percentage < 70) {
        return "D";
    } else if (percentage >= 0 && percentage < 60) {
        return "F";
    } else {
        return "Invalid percentage";
    }
}
----

The AND operator `&&` used in this example means that in order to return `"B"`, for example, the percentage must be greater than or equal to `80` _and_ less than `90`.
If either of those conditions is not met, the program will move on to the next `else if` statement.


// TODO: In the future, maybe a video on logical operators and range checking?


=== `switch` Statements

Java includes a structure called a `switch` statement that can be used to choose between multiple options.
It is essentially another way to write an `if-else if` structure, but it can be more readable and easier to write in some situations.
I generally consider `switch` structures to be optional--you can complete all of the assignments in this course without using them--but they are a useful tool to have in your programming toolbox.
And since you see them often in code written by others, it's good to know how they work.

The basic structure of a `switch` statement is as follows:
[source,java]
----
switch (expression) {
    case value1:
        // Code to be executed if expression equals value1
        break;
    case value2:
        // Code to be executed if expression equals value2
        break;
    case value3:
        // Code to be executed if expression equals value3
        break;
    default:
        // Code to be executed if expression doesn't match any case
}
----

The `expression` in the parentheses after the `switch` keyword is evaluated, and then the program will jump to the `case` that matches the value of the expression.
If there is no match, the program will execute the `default` block, if it is present.

The `break` statement is used to exit the `switch` block due to a behavior of `switch` that can be confusing to beginners, known as _fall-through_.
If you don't include a `break` statement at the end of a `case` block, the program will continue executing the code in the next `case` block, even if the value of the expression doesn't match the `case`.
This can be useful in some situations, but it's generally not what you want, so you'll usually see a `break` statement at the end of each `case` block.

.Example of a `switch` statement.
[source,java]
----
public void trafficInstructions(String lightColor) {
    switch (lightColor) {
        case "red":
            System.out.println("Stop!");
            break;
        case "yellow":
            System.out.println("Slow down!");
            break;
        case "green":
            System.out.println("Go!");
            break;
        default:
            System.out.println("Invalid light color.");
    }
}
----

// TODO: In the future, maybe a video on switch statements?

=== Solution Walkthrough

In "solution walkthrough" videos, I give a problem/prompt that is similar to the kinds of work I assign, and then I record myself writing a solution. It's not absolutely mandatory to watch this video, but students report that these videos are particularly helpful.

.Time To Watch!
****
Decisions - Java Solution Walkthrough

video::7khBJXDXirs[youtube, list=PL_Lc2HVYD16Y-vLXkIgggjYrSdF5DEFnU]


// https://www.youtube.com/watch?v=7khBJXDXirs

// TODO: Rebuild the solution walkthrough file

Solution file from video:

_Not yet available!_
// * Completed code: https://github.com/timmcmichael/EMCCTimFiles/blob/main/OOP%20with%20Java%20(CIS150AB)/03%20Methods/Percentages.java[`Percentages.java`^]
****

'''

:sectnums!:
=== Check Yourself Before You Wreck Yourself (on the assignments)

==== Can you answer these questions?

****

1. Explain what Boolean expressions are and how they are used to make decisions in Java.

2. Explain the difference between a relational operator and a logical operator.

3. What is the difference between an `if` statement and an `if-else` statement?

4. How can you write code that runs one code block from multiple options?

****
:sectnums: