:imagesdir: images
:sourcedir: source
// The following corrects the directories if this is included in the index file.
ifeval::["{docname}" == "index"]
:imagesdir: chapter-5-decisions/images
:sourcedir: chapter-5-decisions/source
endif::[]

== 0101 - Decisions (Chapter 5)

=== #Content coming soon!#


// Example: two buttons on a food scale. On/Zero/Off button and switch between oz and grams. Multifunction button could be written a couple different ways (logical operators or nested if statements)


// === #Content for this module is under construction. For now, the section headers below direct you to the corresponding chapter in our required textbook so that you can start right away.#

// TODO: Upload source files to GitHub archive
// #This section is not finished, but in the meantime this content is covered in section x.x (page xxx) in the textbook.#

.Help Make These Materials Better!
****
I am actively working to complete and revise this eBook and the accompanying videos. Please consider using the following link to provide feedback and notify me of typos, mistakes, and suggestions for either the eBook or videos:

https://forms.gle/4173pZ1yPuNX7pku6[CIS150AB Course Materials Feedback (Google Form)^]
****

// === What's the Point?
// * 

_Source code examples from this chapter and associated videos are available on https://github.com/timmcmichael/EMCCTimFiles/tree/4bf0da6df6f4fe3e3a0ccd477b4455df400cffb6/OOP%20with%20Java%20(CIS150AB)/05%20Decisions[GitHub^]._

// ''''

=== Boolean Expressions

Until now, our programs have all executed very sequentially and predictably--one line of code after another.
How boring!
To give our programs the ability to _branch_ and execute different code based on different conditions, we need to introduce the concept of _decisions_.

In computer programming, a decision is made based on a *boolean expression*, which is an expression that evaluates to either `true` or `false`.
Think of them as questions that can be answered with a simple "yes" or "no".
_Is this student's GPA high enough to qualify for the scholarship? Has this cell phone customer used all of their data? Did the user enter "exit"?_

The `true` or `false` value of a boolean expression can be used to determine which code block will execute next, so it's important to understand how they work. 


.Time To Watch!
****
Boolean Logic in Java

// https://youtu.be/npMQkQ2oCAU

video::npMQkQ2oCAU[youtube, list=PL_Lc2HVYD16Y-vLXkIgggjYrSdF5DEFnU]
// File from video:

// * N/A
****

==== Boolean Values

The simplest way to use boolean in Java are the keywords `true` and `false`.
These can be assigned to variables of type `boolean`:

[source,java]
----
boolean isTimAmazing = true;
boolean isClassBoring = false;
----

==== Relational Operations
Also known as _comparison operations_, relational operations are expressions that compare two values. 
You will remember them from math class._Is `x` greater than `y`? Is `a` less than or equal to `10`? Is `c` equal to `d`?_
Relational operators, like arithmetic operators, are _binary_ operators that require two operands. 
In other words, you need two values to compare.
In your math class, you could draw symbols that aren't on your keyboard, like a &#8805; for "greater than or equal to."
In Java, where we have to stick with stuff on our keyboard, we use the following symbols:

.Java arithmetic operators
[cols="1,5", %header, stripes=even,width="50%"]
|===
|Operator |Description
| `==`
| Equality (checks if two values are equal)
| `!=`
| Inequality (checks if two values are not equal)
| `<`
| Less-than
| `>`
| Greater-than
| `&lt;&#61;`
| Less-than-or-equal-to
| `>=`
| Greater-than-or-equal-to operator.
|===

A relational operation will alway evaluate to either `true` or `false`.
We can store that result in a `boolean` variable, as shown below, and we'll also learn how to use these expressions in `if` statements later in this chapter.

[source,java]
----
boolean canBuyAlcohol = age >= 21;
boolean isNegative = number < 0;
----

These assignment statements work like any other: the expression to the right of the equals symbol is evaluated, and the result is stored in the variable on the left.

==== Testing a String for Equality

In Java, you can't use the `==` operator to compare two strings.
The following code will not work as you might expect:

.Example of an incorrect `String` comparison.
[source,java]
----
// Should output "true", but (sometimes) doesn't
String name = "Paul McCartney";
System.out.print("Is this person Paul McCartney?");
System.out.println(name == "Paul McCartney");   // DON'T DO THIS!
----

The `==` operator does not compare the contents of the strings, but rather the memory addresses where the strings are stored.
Due to the nuances of how the Java runtime handles `String` objects, this code will work sometimes, by coincidence, but it's not reliable.

Instead, you'll need to use the `equals()` method, which is a method of the `String` class and gets called using dot notation.
This method will examine the contents of the strings and return `true` if they are the same, and `false` if they are different.

.Example of a correct `String` comparison.
[source,java]
----
// Outputs "true"
String name = "Paul McCartney";
System.out.print("Is this person Paul McCartney? ");
System.out.println(name.equals("Paul McCartney"));
----

=== if Statements

The `if` statement is the most basic decision-making structure in Java.
It allows you to execute a block of code only if a certain condition is true.

The syntax of an `if` statement is the keyword `if`, followed by a boolean expression in parentheses, followed by a block of code in curly braces.
If the boolean expression evaluates to `true`, the block of code will execute.
If the boolean expression evaluates to `false`, the block of code will be skipped.
In either case the program will continue executing the next line of code after the `if`-block.

.Example of an `if` Statement.
[source,java]
----
int age = 20;
if (age < 21) {
    System.out.println("You can't buy alcohol.");
}
System.out.println("Keep that in mind when you go to the store!");
----

In this example, the `if` statement checks if the variable `age` is less than `21`.
Since `20` is less than `21`, the boolean expression evaluates to `true`, and the block of code inside the `if` statement is executed--and it prints "You can't buy alcohol."
The program then continues to the next line of code, which prints "Keep that in mind when you go to the store!"

If the value of `age` were `22`, the boolean expression would evaluate to `false`, and the block of code inside the `if` statement would be skipped.
The program would then continue to the next line of code, which prints "Keep that in mind when you go to the store!"

Keep in mind, the parentheses after the `if` keyword can contain any boolean expression--not just this simple example.

=== Adding an `else` Block

An `if` statement simply determines whether or not to execute a single block of code.
If you want choose between two blocks of code, you can add an `else` block to the `if` statement.
The syntax is simple: after the `if` block, add the keyword `else`, followed by a block of code in curly braces.

.Example of an `if-else` Statement.
[source,java]
----
int age = 20;
if (age < 21) {
    System.out.println("You can't buy alcohol.");
}
else {
    System.out.println("You can buy alcohol.");
}
System.out.println("Keep that in mind when you go to the store!");
----

An `if-else` statement will always execute one block of code or the other, but never both.
Basically, it's an either-or situation.

// .Time To Watch!
// ****
// if and if-else Statements in Java

// video::PR6u4KvAkas[youtube, list=PL_Lc2HVYD16Y-vLXkIgggjYrSdF5DEFnU]
// File from video:

// * https://raw.githubusercontent.com/timmcmichael/EMCCTimFiles/refs/heads/main/OOP%20with%20Java%20(CIS150AB)/HelloWorld.java[HelloWorld.java]
// ****

=== The `if else if` Structure

The `if-else` structure is great for choosing between two blocks of code, but what if you have more than two options?
To handle this, you can chain multiple `if-else` statements together.

.Example of an `if-else if` Statement.
[source,java]
----
int age = 20;
if (age < 18) {
    System.out.println("You can't vote.");
}
else if (age < 21) {
    System.out.println("You can vote, but you can't buy alcohol.");
}
else {
    System.out.println("You can vote and buy alcohol.");
}
----

In this example, the program will print "You can't vote." if the age is less than `18`, "You can vote, but you can't buy alcohol." if the age is less than `21`, and "You can vote and buy alcohol." if the age is `21` or older.

Basically, the program checks each boolean expression until one evaluates to `true`, and then executes the corresponding block of code.
Once it was executed a code block, it will skip the rest of the `if-else` structure.
If it never finds a `true` condition, it will execute the block of code in the `else` block, if one is present.

An `if-else if` structure can execute, at most, one block of code. 
If an `else` block is included at the end, that guarantees that exactly one block of code will execute.

Compare that to a series of `if` statements without any else blocks.

.Example of a Series of `if` Statements.
[source,java]
----
if (age < 18) {
    System.out.println("You can't vote.");
}
if (age >= 18) {
    System.out.println("You can vote.");
}
if (age < 21) {
    System.out.println("You can't buy alcohol.");
}
if (age >= 21) {
    System.out.println("You can buy alcohol.");
}
----

In this example, each `if` statement is independent of the others and they all will be evaluated. regardless of the outcome of the previous `if` statement.
Since `20` is greater than `18`, the first `if` block will be skipped, but the second `if` block will execute.
Since `20` is less than `21`, the third `if` block will execute, but the fourth `if` block will be skipped.
The output will be:

[source]
----
You can vote.
You can't buy alcohol.
----

With a series of separate `if statements, it's possible that no blocks of code will execute, and it's possible that every block of code will execute. 
And any combination in between is possible, as well.

=== Nested if-else Statements

If we want a block of code to execute only if two different conditions are met, we can place `if` statements inside of each other--which is called _nesting_.
Nested if statements check multiple conditions in a hierarchical way: if one condition is met, it will proceed and check the next condition; if the first condition is not met, it will skip the inner `if` block.

.Basic structure of a nested `if-else` statement.
[source,java]
----
if (condition1) {
    if (condition2) {
        // executes if both condition1 and condition2 are true
    }
    else {
        // executes if condition1 is true and condition2 is false
    }
}
else {
    // executes if condition1 is false
}
----

In the example below, the program will print "You can vote and buy alcohol." if the age is `21` or older and the person is a U.S. citizen.

.Example of a Nested `if-else` Statement.
[source,java]
----
int age = 20;
boolean isCitizen = true;
if (age >= 21) {
    if (isCitizen) {
        System.out.println("You can vote and buy alcohol.");
    }
    else {
        System.out.println("You can buy alcohol, but you can't vote.");
    }
}
else {
    System.out.println("You can't vote or buy alcohol.");
}
----





// .Time To Watch!
// ****
// Nested if-else Statements in Java

// video::PR6u4KvAkas[youtube, list=PL_Lc2HVYD16Y-vLXkIgggjYrSdF5DEFnU]
// File from video:

// * https://raw.githubusercontent.com/timmcmichael/EMCCTimFiles/refs/heads/main/OOP%20with%20Java%20(CIS150AB)/HelloWorld.java[HelloWorld.java]
// ****


=== Logical Operators

// .Time To Watch!
// ****
// Logical Operators in Java

// video::PR6u4KvAkas[youtube, list=PL_Lc2HVYD16Y-vLXkIgggjYrSdF5DEFnU]
// File from video:

// * https://raw.githubusercontent.com/timmcmichael/EMCCTimFiles/refs/heads/main/OOP%20with%20Java%20(CIS150AB)/HelloWorld.java[HelloWorld.java]
// ****

=== OPTIONAL: The Ternary Operator


// .Time To Watch!
// ****
// The Ternary Operator in Java

// video::PR6u4KvAkas[youtube, list=PL_Lc2HVYD16Y-vLXkIgggjYrSdF5DEFnU]
// File from video:

// * https://raw.githubusercontent.com/timmcmichael/EMCCTimFiles/refs/heads/main/OOP%20with%20Java%20(CIS150AB)/HelloWorld.java[HelloWorld.java]
// ****



=== OPTIONAL: switch Statements


// .Time To Watch!
// ****
// switch Statements in Java

// video::PR6u4KvAkas[youtube, list=PL_Lc2HVYD16Y-vLXkIgggjYrSdF5DEFnU]
// File from video:

// * https://raw.githubusercontent.com/timmcmichael/EMCCTimFiles/refs/heads/main/OOP%20with%20Java%20(CIS150AB)/HelloWorld.java[HelloWorld.java]
// ****


// === Check Your Learning
//
// ==== Can you answer these questions?

// ****
// 
// 1. 
//
// 2. 
//
// ****