name: Check Broken Links

on:
  workflow_dispatch: # Allows manual triggering of the workflow
  push:
    branches:
      - gh-pages

jobs:
  check-links:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Run Link Checker
      uses: lycheeverse/lychee-action@v1.6.0
      with:
        args: --base-url https://timmcmichael.github.io/skimpy-oop/
