name: Check Links on GitHub Pages

on:
  push:
    branches:
      - gh-pages  # Runs when the site is updated
  schedule:
    - cron: '0 0 * * 0'  # Runs weekly on Sundays
  pull_request:
    branches:
      - gh-pages  # Runs on PRs to gh-pages

jobs:
  link-checker:
    runs-on: ubuntu-latest

    steps:
      - name: Run Lychee Broken Link Checker
        uses: lycheeverse/lychee-action@v1.8.0
        with:
          args: --verbose --fail --output lychee-report.json https://timmcmichael.github.io/skimpy-oop/

      - name: Upload link check results
        uses: actions/upload-artifact@v3
        with:
          name: link-check-results
          path: ./results/
