name: Build PDF Output

on:
  workflow_dispatch:

jobs:
  build-light:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Clean output directory
        run: rm -rf output-light

      - name: List css files
        run: ls -la && more css/asciidoctor.css && more index.adoc

      - name: Generate Light Theme
        run: |
          docker run --rm \
            -u $(id -u):$(id -g) \
            -v ${{ github.workspace }}:/documents \
            docker.io/asciidoctor/docker-asciidoctor \
            /bin/bash -c "mkdir -p /documents/.gem && \
                          export GEM_HOME=/documents/.gem && \
                          export GEM_PATH=/documents/.gem && \
                          export PATH=/documents/.gem/bin:$PATH && \
                          gem install asciidoctor-multipage && \
                          gem install asciidoctor-pdf && \
                          gem install pygments.rb && \
                          gem install asciidoc-diagram && \
                          asciidoctor-pdf -r asciidoctor-diagram -D /documents/output-light  -a source-highlighter=pygments /documents/index.adoc"

      - name: List output files
        run: ls -la output-light

      - name: Commit and push changes
        env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            git config --global user.name "github-actions[bot]"
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/timmcmichael/skimpy-oop.git
            # git config --global pull.rebase true
            git add .
            git commit -m "Generate PDF file" || echo "No changes to commit"
            git pull --rebase --autostash origin main
            git push origin HEAD:main
